/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppAbout {}
  interface AppGpssettings {}
  interface AppHistory {}
  interface AppHome {}
  interface AppHome {}
  interface AppOffline {}
  interface AppRoot {}
  interface AppTabs {}
}

declare global {


  interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {}
  var HTMLAppAboutElement: {
    prototype: HTMLAppAboutElement;
    new (): HTMLAppAboutElement;
  };

  interface HTMLAppGpssettingsElement extends Components.AppGpssettings, HTMLStencilElement {}
  var HTMLAppGpssettingsElement: {
    prototype: HTMLAppGpssettingsElement;
    new (): HTMLAppGpssettingsElement;
  };

  interface HTMLAppHistoryElement extends Components.AppHistory, HTMLStencilElement {}
  var HTMLAppHistoryElement: {
    prototype: HTMLAppHistoryElement;
    new (): HTMLAppHistoryElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppOfflineElement extends Components.AppOffline, HTMLStencilElement {}
  var HTMLAppOfflineElement: {
    prototype: HTMLAppOfflineElement;
    new (): HTMLAppOfflineElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppTabsElement extends Components.AppTabs, HTMLStencilElement {}
  var HTMLAppTabsElement: {
    prototype: HTMLAppTabsElement;
    new (): HTMLAppTabsElement;
  };
  interface HTMLElementTagNameMap {
    'app-about': HTMLAppAboutElement;
    'app-gpssettings': HTMLAppGpssettingsElement;
    'app-history': HTMLAppHistoryElement;
    'app-home': HTMLAppHomeElement;
    'app-home': HTMLAppHomeElement;
    'app-offline': HTMLAppOfflineElement;
    'app-root': HTMLAppRootElement;
    'app-tabs': HTMLAppTabsElement;
  }
}

declare namespace LocalJSX {
  interface AppAbout extends JSXBase.HTMLAttributes<HTMLAppAboutElement> {}
  interface AppGpssettings extends JSXBase.HTMLAttributes<HTMLAppGpssettingsElement> {}
  interface AppHistory extends JSXBase.HTMLAttributes<HTMLAppHistoryElement> {}
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppOffline extends JSXBase.HTMLAttributes<HTMLAppOfflineElement> {}
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface AppTabs extends JSXBase.HTMLAttributes<HTMLAppTabsElement> {}

  interface IntrinsicElements {
    'app-about': AppAbout;
    'app-gpssettings': AppGpssettings;
    'app-history': AppHistory;
    'app-home': AppHome;
    'app-home': AppHome;
    'app-offline': AppOffline;
    'app-root': AppRoot;
    'app-tabs': AppTabs;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


